<a href="https://colab.research.google.com/github/chamikasudusinghe/nocml/blob/master/fft_i3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Module Imports for Data Fetiching and Visualization

In [0]:
import time
import pandas as pd
import numpy as np
import math
import pickle
from functools import reduce

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [0]:
from google.colab import drive
drive.mount('/content/drive')
root_dir = "/content/drive/My Drive/model-i3-less-features"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
from sklearn import preprocessing
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [0]:
import statsmodels.api as sm
from sklearn import metrics

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

Importing Dataset from GitHub

Test Data

In [0]:
df0_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r0/4-fft-malicious-n-0-6-9-15-m-1-12-r0.csv?token=AKVFSODNRUSG6XK2HQVZRVS64H5FK')
df0_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r0/4-fft-malicious-n-0-6-9-15-m-1-7-r0.csv?token=AKVFSOC2SKUIGTKKWRM2JIC64H3ZA')
df0_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r0/4-fft-malicious-n-0-6-9-15-m-11-12-r0.csv?token=AKVFSOCLRNR2324NBTEBAES64H3ZG')
df0_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r0/4-fft-malicious-n-0-6-9-15-m-7-11-r0.csv?token=AKVFSOEPMNCCTKPNX4MNWYS64H3ZM')
df0_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r0/4-fft-malicious-n-0-6-9-15-m-7-12-r0.csv?token=AKVFSODEXN6OEHVKJDJWR3S64H3ZS')

In [0]:
df1_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r1/4-fft-malicious-n-0-6-9-15-m-1-12-r1.csv?token=AKVFSOFFRJMGBGR3VCWEU7264H5SA')
df1_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r1/4-fft-malicious-n-0-6-9-15-m-1-7-r1.csv?token=AKVFSOBMHF2KHMUJCSTNEQC64H374')
df1_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r1/4-fft-malicious-n-0-6-9-15-m-11-12-r1.csv?token=AKVFSOHEATSH7OHVBVTRMDS64H4AC')
df1_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r1/4-fft-malicious-n-0-6-9-15-m-7-11-r1.csv?token=AKVFSOGXOKXCV4ZQWTTFUVC64H4AI')
df1_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r1/4-fft-malicious-n-0-6-9-15-m-7-12-r1.csv?token=AKVFSOECUNR2NOTT43OZCN264H4AS')

In [0]:
df2_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r2/4-fft-malicious-n-0-6-9-15-m-1-12-r2.csv?token=AKVFSOFEQ5GDY4WA54K55EK64H6BE')
df2_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r2/4-fft-malicious-n-0-6-9-15-m-1-7-r2.csv?token=AKVFSOGP7ZM3CRJGVZJ65KS64H6BK')
df2_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r2/4-fft-malicious-n-0-6-9-15-m-11-12-r2.csv?token=AKVFSOHDUCR2QDO2TC7WA5264H6BQ')
df2_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r2/4-fft-malicious-n-0-6-9-15-m-7-11-r2.csv?token=AKVFSOEWGKQ3QQ6MYOHPL4264H6BU')
df2_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r2/4-fft-malicious-n-0-6-9-15-m-7-12-r2.csv?token=AKVFSOC322DAT7QDRMUHR2S64H6B2')

In [0]:
df3_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r3/4-fft-malicious-n-0-6-9-15-m-1-12-r3.csv?token=AKVFSOGQL7JXHQ3RM7XXAFC64H6VC')
df3_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r3/4-fft-malicious-n-0-6-9-15-m-1-7-r3.csv?token=AKVFSOAW5QEWJJCHF5UCUNS64H6VG')
df3_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r3/4-fft-malicious-n-0-6-9-15-m-11-12-r3.csv?token=AKVFSOFHXNZAWS5H4YTTUI264H6VM')
df3_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r3/4-fft-malicious-n-0-6-9-15-m-7-11-r3.csv?token=AKVFSOHH76DGKR3NQE3P23264H6VS')
df3_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r3/4-fft-malicious-n-0-6-9-15-m-7-12-r3.csv?token=AKVFSOHISKBOPBTRWGSNTKC64H6V4')

In [0]:
df4_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r4/4-fft-malicious-n-0-6-9-15-m-1-12-r4.csv?token=AKVFSOD3IUIJAZD6FXCMFBS64H7KO')
df4_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r4/4-fft-malicious-n-0-6-9-15-m-1-7-r4.csv?token=AKVFSOCX7XMEK52T3TD3MNK64H7KU')
df4_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r4/4-fft-malicious-n-0-6-9-15-m-11-12-r4.csv?token=AKVFSOCETXA66KAOE7H5BI264H7K2')
df4_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r4/4-fft-malicious-n-0-6-9-15-m-7-11-r4.csv?token=AKVFSOB7Q3BEIMGX3RTEYP264H7LA')
df4_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r4/4-fft-malicious-n-0-6-9-15-m-7-12-r4.csv?token=AKVFSOCTYHLY4LXMC262ITC64H7LG')

In [0]:
df5_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r5/4-fft-malicious-n-0-6-9-15-m-1-12-r5.csv?token=AKVFSODXRV4CVCNE53U2EQ264IAQA')
df5_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r5/4-fft-malicious-n-0-6-9-15-m-1-7-r5.csv?token=AKVFSOBQ5MKQHIV6XDGFJUK64IAQG')
df5_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r5/4-fft-malicious-n-0-6-9-15-m-11-12-r5.csv?token=AKVFSOHDOIHYUVOJJK4ZL6264IAQK')
df5_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r5/4-fft-malicious-n-0-6-9-15-m-7-11-r5.csv?token=AKVFSOFFFOCILTHOTTIP7XS64IAQO')
df5_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r5/4-fft-malicious-n-0-6-9-15-m-7-12-r5.csv?token=AKVFSOGGMXIXWZYZVZNUDD264IAQS')

In [0]:
df6_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r6/4-fft-malicious-n-0-6-9-15-m-1-12-r6.csv?token=AKVFSOE74S6OVNYGLW35I5S64IA62')
df6_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r6/4-fft-malicious-n-0-6-9-15-m-1-7-r6.csv?token=AKVFSOBOGMIEARZA7GYQFFK64IA66')
df6_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r6/4-fft-malicious-n-0-6-9-15-m-11-12-r6.csv?token=AKVFSOBV6TIE2PVMLDJP3MC64IA7E')
df6_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r6/4-fft-malicious-n-0-6-9-15-m-7-11-r6.csv?token=AKVFSOC43VEQFYVPAG6RWZC64IA7K')
df6_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r6/4-fft-malicious-n-0-6-9-15-m-7-12-r6.csv?token=AKVFSOBIVHJPJLC3NTFQUU264IA7S')

In [0]:
df7_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r7/4-fft-malicious-n-0-6-9-15-m-1-12-r7.csv?token=AKVFSOARFLPZJWJVCWBXXU264IBME')
df7_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r7/4-fft-malicious-n-0-6-9-15-m-1-7-r7.csv?token=AKVFSOF5EQMTX3P5FEFELP264IBMK')
df7_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r7/4-fft-malicious-n-0-6-9-15-m-11-12-r7.csv?token=AKVFSOALZBH75OCNCP4IFAC64IBMO')
df7_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r7/4-fft-malicious-n-0-6-9-15-m-7-11-r7.csv?token=AKVFSOFUPS2W5NLNPBCEI6C64IBMU')
df7_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r7/4-fft-malicious-n-0-6-9-15-m-7-12-r7.csv?token=AKVFSOBFSCGUOWEKU45GQJC64IBMY')

In [0]:
df8_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r8/4-fft-malicious-n-0-6-9-15-m-1-12-r8.csv?token=AKVFSOEZEP3GBKUQVWOE5YS64IBYY')
df8_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r8/4-fft-malicious-n-0-6-9-15-m-1-7-r8.csv?token=AKVFSOBXLJSNDFVPS5OKRX264IBY6')
df8_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r8/4-fft-malicious-n-0-6-9-15-m-11-12-r8.csv?token=AKVFSOFWAL5BIHKMMLLP6PK64IBZA')
df8_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r8/4-fft-malicious-n-0-6-9-15-m-7-11-r8.csv?token=AKVFSOGP5X53F3VNH24GAEC64IBZG')
df8_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r8/4-fft-malicious-n-0-6-9-15-m-7-12-r8.csv?token=AKVFSOFXUMXLCOZACXGY67S64IBZO')

In [0]:
df9_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r9/4-fft-malicious-n-0-6-9-15-m-1-12-r9.csv?token=AKVFSOGTVH2QWJI32FP6WOC64ICO2')
df9_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r9/4-fft-malicious-n-0-6-9-15-m-1-7-r9.csv?token=AKVFSOD3QJE3XVUWKCDOMPC64ICO6')
df9_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r9/4-fft-malicious-n-0-6-9-15-m-11-12-r9.csv?token=AKVFSOBUDSDSNEWLAJDABC264ICPE')
df9_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r9/4-fft-malicious-n-0-6-9-15-m-7-11-r9.csv?token=AKVFSOECRP4HXQX4ENUBQZC64ICPK')
df9_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r9/4-fft-malicious-n-0-6-9-15-m-7-12-r9.csv?token=AKVFSOE7BVO6CPCMR5SKKDC64ICPO')

In [0]:
df10_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r10/4-fft-malicious-n-0-6-9-15-m-1-12-r10.csv?token=AKVFSOFSBMO5VTREN4OLTLK64IDLG')
df10_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r10/4-fft-malicious-n-0-6-9-15-m-1-7-r10.csv?token=AKVFSOEF4XA5WNRC7LC3N2K64IDLM')
df10_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r10/4-fft-malicious-n-0-6-9-15-m-11-12-r10.csv?token=AKVFSOC5GRVHDVGK4QBU7MS64IDLO')
df10_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r10/4-fft-malicious-n-0-6-9-15-m-7-11-r10.csv?token=AKVFSOGZ3FY6NUK67TUVDZ264IDLU')
df10_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r10/4-fft-malicious-n-0-6-9-15-m-7-12-r10.csv?token=AKVFSODYX7XNLDYEDSHMVV264IDLY')

In [0]:
df11_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r11/4-fft-malicious-n-0-6-9-15-m-1-12-r11.csv?token=AKVFSOG3LUFWAPSIQQXLUS264IETE')
df11_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r11/4-fft-malicious-n-0-6-9-15-m-1-7-r11.csv?token=AKVFSOG6IDUOYD6GREDN4KS64IETK')
df11_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r11/4-fft-malicious-n-0-6-9-15-m-11-12-r11.csv?token=AKVFSODRUR7UPSJ442ZW3QS64IETO')
df11_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r11/4-fft-malicious-n-0-6-9-15-m-7-11-r11.csv?token=AKVFSOBMHE2VPWA7AV345VC64IETY')
df11_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r11/4-fft-malicious-n-0-6-9-15-m-7-12-r11.csv?token=AKVFSOB4W4XKIGMJZRLIAFC64IEUC')

In [0]:
df12_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r12/4-fft-malicious-n-0-6-9-15-m-1-12-r12.csv?token=AKVFSOEZ6DTXKHPQ5QU2DV264IE66')
df12_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r12/4-fft-malicious-n-0-6-9-15-m-1-7-r12.csv?token=AKVFSOG5Y74EOXY6IR5YLBS64IE7C')
df12_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r12/4-fft-malicious-n-0-6-9-15-m-11-12-r12.csv?token=AKVFSOG5ETKKLOKQGIC57UK64IE7G')
df12_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r12/4-fft-malicious-n-0-6-9-15-m-7-11-r12.csv?token=AKVFSOBTH4ZO5PWKGDY46GS64IE7K')
df12_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r12/4-fft-malicious-n-0-6-9-15-m-7-12-r12.csv?token=AKVFSOCNXJ4POVY3RMLEBO264IE7Q')

In [0]:
df13_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r13/4-fft-malicious-n-0-6-9-15-m-1-12-r13.csv?token=AKVFSOF4X4R7BFTB6HZHQIS64IFQG')
df13_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r13/4-fft-malicious-n-0-6-9-15-m-1-7-r13.csv?token=AKVFSOG2HBE2OOCRWJ6HH4S64IFQK')
df13_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r13/4-fft-malicious-n-0-6-9-15-m-11-12-r13.csv?token=AKVFSOHUO4J3I3YP4UWHOE264IFQQ')
df13_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r13/4-fft-malicious-n-0-6-9-15-m-7-11-r13.csv?token=AKVFSOEFJIGQF2P3577ZJYS64IFQW')
df13_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r13/4-fft-malicious-n-0-6-9-15-m-7-12-r13.csv?token=AKVFSOA5XKKUNVPBV7KCNMC64IFQ4')

In [0]:
df14_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r14/4-fft-malicious-n-0-6-9-15-m-1-12-r14.csv?token=AKVFSODULOIMM7C3BPSK5RK64IGKK')
df14_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r14/4-fft-malicious-n-0-6-9-15-m-1-7-r14.csv?token=AKVFSOFSHA3PGSE3JH2NAYK64IGKQ')
df14_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r14/4-fft-malicious-n-0-6-9-15-m-11-12-r14.csv?token=AKVFSOELVZU2URT3BMUHD3K64IGKU')
df14_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r14/4-fft-malicious-n-0-6-9-15-m-7-11-r14.csv?token=AKVFSOFONKMF3HDQAUQZIFS64IGK2')
df14_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r14/4-fft-malicious-n-0-6-9-15-m-7-12-r14.csv?token=AKVFSOA3QNMERJDLARYJZXK64IGLA')

In [0]:
df15_1 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r15/4-fft-malicious-n-0-6-9-15-m-1-12-r15.csv?token=AKVFSOHF734NBY65CTLE7FC64IHT6')
df15_2 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r15/4-fft-malicious-n-0-6-9-15-m-1-7-r15.csv?token=AKVFSOEFVU32QE75VKKBXW264IHUE')
df15_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r15/4-fft-malicious-n-0-6-9-15-m-11-12-r15.csv?token=AKVFSOEKVR7IMBRGAL7WZHS64IHUI')
df15_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r15/4-fft-malicious-n-0-6-9-15-m-7-11-r15.csv?token=AKVFSOBS6YMYZI4SLRNMMJ264IHUM')
df15_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r15/4-fft-malicious-n-0-6-9-15-m-7-12-r15.csv?token=AKVFSOA57BNEABRLUAD7OLC64IHUQ')

In [0]:
print(df15_5.shape)
df15_5

(123780, 26)

        timestamp  outport  ...  vnet_vc_cc_index  target
0               7        3  ...                27       0
1              19        3  ...                27       0
2              98        0  ...               340       0
3              99        0  ...               340       0
4             100        0  ...               340       0
...           ...      ...  ...               ...     ...
123775    3280623        3  ...               165       0
123776    3280630        3  ...               165       0
123777    3280637        3  ...               165       0
123778    3280638        3  ...                36       0
123779    3280683        0  ...               189       0

[123780 rows x 26 columns]

In [0]:
def roundup(x):
  return int(math.ceil(x / 1000.0)) * 1000

In [0]:
def timecount(df):
    timearr = []
    interval = 999
    count = 0
    for index, row in df.iterrows():
        if row["timestamp"]<=interval :
            count+=1
        else:
            timearr.append([interval+1,count])
            count=1
            if (row["timestamp"] == roundup(row["timestamp"])):
              interval = row["timestamp"]+999
            else:
              interval = roundup(row["timestamp"])-1
    timearr.append([interval+1,count])
    return timearr

In [0]:
def standardize(df):
  test_X = df.drop(columns=['target','timestamp','src_ni','src_router','dst_ni','dst_router','inport','cache_coherence_type','flit_id','flit_type','vnet','current_hop','hop_percentage','port_index','cache_coherence_vnet_index','vnet_vc_cc_index'])
  test_Y = df['target']
  x = test_X.values
  min_max_scaler = preprocessing.MinMaxScaler()
  columns = test_X.columns
  x_scaled = min_max_scaler.fit_transform(x)
  test_X = pd.DataFrame(x_scaled)
  test_X.columns = columns
  print(test_X[test_X.duplicated()].shape)
  return test_X,test_Y

In [0]:
xgb_r0 = pickle.load(open(root_dir+"/xgbc-r0l-i3.pickle.dat", "rb"))
xgb_r1 = pickle.load(open(root_dir+"/xgbc-r1l-i3.pickle.dat", "rb"))
xgb_r2 = pickle.load(open(root_dir+"/xgbc-r2l-i3.pickle.dat", "rb"))
xgb_r3 = pickle.load(open(root_dir+"/xgbc-r3l-i3.pickle.dat", "rb"))
xgb_r4 = pickle.load(open(root_dir+"/xgbc-r4l-i3.pickle.dat", "rb"))
xgb_r5 = pickle.load(open(root_dir+"/xgbc-r5l-i3.pickle.dat", "rb"))
xgb_r6 = pickle.load(open(root_dir+"/xgbc-r6l-i3.pickle.dat", "rb"))
xgb_r7 = pickle.load(open(root_dir+"/xgbc-r7l-i3.pickle.dat", "rb"))
xgb_r8 = pickle.load(open(root_dir+"/xgbc-r8l-i3.pickle.dat", "rb"))
xgb_r9 = pickle.load(open(root_dir+"/xgbc-r9l-i3.pickle.dat", "rb"))
xgb_r10 = pickle.load(open(root_dir+"/xgbc-r10l-i3.pickle.dat", "rb"))
xgb_r11 = pickle.load(open(root_dir+"/xgbc-r11l-i3.pickle.dat", "rb"))
xgb_r12 = pickle.load(open(root_dir+"/xgbc-r12l-i3.pickle.dat", "rb"))
xgb_r13 = pickle.load(open(root_dir+"/xgbc-r13l-i3.pickle.dat", "rb"))
xgb_r14 = pickle.load(open(root_dir+"/xgbc-r14l-i3.pickle.dat", "rb"))
xgb_r15 = pickle.load(open(root_dir+"/xgbc-r15l-i3.pickle.dat", "rb"))

In [0]:
df0_1.shape

(140312, 26)

In [0]:
def window(j):

  timearr0 = timecount(df0_2)
  timearr1 = timecount(df1_2)
  timearr2 = timecount(df2_2)
  timearr3 = timecount(df3_2)
  timearr4 = timecount(df4_2)
  timearr5 = timecount(df5_2)
  timearr6 = timecount(df6_2)
  timearr7 = timecount(df7_2)
  timearr8 = timecount(df8_2)
  timearr9 = timecount(df9_2)
  timearr10 = timecount(df10_2)
  timearr11 = timecount(df11_2)
  timearr12 = timecount(df12_2)
  timearr13 = timecount(df13_2)
  timearr14 = timecount(df14_2)
  timearr15 = timecount(df15_2)

  max_limit = max(timearr0[-1],timearr1[-1],timearr2[-1],timearr3[-1],timearr4[-1],timearr5[-1],timearr6[-1],timearr7[-1],timearr8[-1],timearr9[-1],timearr10[-1],timearr11[-1],timearr12[-1],timearr13[-1],timearr14[-1],timearr15[-1])

  print(max_limit[0])
  
  def prediction(df,timearr,xgb):

    test_X,test_Y = standardize (df)
    counter = timearr[0][1]
    result = []
    begin = counter
    text_X0 = test_X[:counter]
    text_Y0 = test_Y[:counter]

    #try:
    #      kfold = KFold(n_splits=10, random_state=7, shuffle = True)
    #      results = cross_val_score(xgb, text_X0, text_Y0, cv=kfold)
    #      result.append([timearr[0][0],results.mean()*100,timearr[0][1]]) 
    #except:
    y_pred_xgbc_test= xgb.predict(text_X0)
    xgbc_score_test = accuracy_score(text_Y0,y_pred_xgbc_test)
    result.append([timearr[0][0],xgbc_score_test*100,timearr[0][1]]) 

    for i in range(1,len(timearr)):

      counter += timearr[i][1]

      text_X0 = test_X[begin:counter]
      text_Y0 = test_Y[begin:counter]

      #try:
      #    kfold = KFold(n_splits=10, random_state=7, shuffle = True)
      #    results = cross_val_score(xgb, text_X0, text_Y0, cv=kfold)
      #    result.append([timearr[i][0],results.mean()*100,timearr[i][1]]) 
      #except:
      y_pred_xgbc_test= xgb.predict(text_X0)
      xgbc_score_test = accuracy_score(text_Y0,y_pred_xgbc_test)
      result.append([timearr[i][0],xgbc_score_test*100,timearr[i][1]])

      begin = counter

    return result

  result0 = prediction(df0_2,timearr0,xgb_r0)
  result1 = prediction(df1_2,timearr1,xgb_r1)
  result2 = prediction(df2_2,timearr2,xgb_r2)
  result3 = prediction(df3_2,timearr3,xgb_r3)
  result4 = prediction(df4_2,timearr4,xgb_r4)
  result5 = prediction(df5_2,timearr5,xgb_r5)
  result6 = prediction(df6_2,timearr6,xgb_r6)
  result7 = prediction(df7_2,timearr7,xgb_r7)
  result8 = prediction(df8_2,timearr8,xgb_r8)
  result9 = prediction(df9_2,timearr9,xgb_r9)
  result10 = prediction(df10_2,timearr10,xgb_r10)
  result11 = prediction(df11_2,timearr11,xgb_r11)
  result12 = prediction(df12_2,timearr12,xgb_r12)
  result13 = prediction(df13_2,timearr13,xgb_r13)
  result14 = prediction(df14_2,timearr14,xgb_r14)
  result15 = prediction(df15_2,timearr15,xgb_r15)

  indexarr = []

  for i in range(1000,int(max_limit[0])+1,1000):
    indexarr.append(i)

  df = pd.DataFrame()
  df = df.assign(index=indexarr)

  df0 = pd.DataFrame()
  df0 = df0.assign(index=[i[0] for i in result0])
  df0 = df0.assign(count0=[i[1] for i in result0])
  df0 = df0.assign(count0_weight=[i[2] for i in result0])
  print(df0.head(15))

  df1 = pd.DataFrame()
  df1 = df1.assign(index=[i[0] for i in result1])
  df1 = df1.assign(count1=[i[1] for i in result1])
  df1 = df1.assign(count1_weight=[i[2] for i in result1])

  df2= pd.DataFrame()
  df2 = df2.assign(index=[i[0] for i in result2])
  df2 = df2.assign(count2=[i[1] for i in result2])
  df2 = df2.assign(count2_weight=[i[2] for i in result2])

  df3 = pd.DataFrame()
  df3 = df3.assign(index=[i[0] for i in result3])
  df3 = df3.assign(count3=[i[1] for i in result3])
  df3 = df3.assign(count3_weight=[i[2] for i in result3])  

  df4 = pd.DataFrame()
  df4 = df4.assign(index=[i[0] for i in result4])
  df4 = df4.assign(count4=[i[1] for i in result4])
  df4 = df4.assign(count4_weight=[i[2] for i in result4])  

  df5 = pd.DataFrame()
  df5 = df5.assign(index=[i[0] for i in result5])
  df5 = df5.assign(count5=[i[1] for i in result5])
  df5 = df5.assign(count5_weight=[i[2] for i in result5])  

  df6 = pd.DataFrame()
  df6 = df6.assign(index=[i[0] for i in result6])
  df6 = df6.assign(count6=[i[1] for i in result6])
  df6 = df6.assign(count6_weight=[i[2] for i in result6])  

  df7= pd.DataFrame()
  df7 = df7.assign(index=[i[0] for i in result7])
  df7 = df7.assign(count7=[i[1] for i in result7])
  df7 = df7.assign(count7_weight=[i[2] for i in result7])  

  df8 = pd.DataFrame()
  df8 = df8.assign(index=[i[0] for i in result8])
  df8 = df8.assign(count8=[i[1] for i in result8])
  df8 = df8.assign(count8_weight=[i[2] for i in result8])  

  df9 = pd.DataFrame()
  df9 = df9.assign(index=[i[0] for i in result9])
  df9 = df9.assign(count9=[i[1] for i in result9])
  df9 = df9.assign(count9_weight=[i[2] for i in result9])  

  df10 = pd.DataFrame()
  df10 = df10.assign(index=[i[0] for i in result10])
  df10 = df10.assign(count10=[i[1] for i in result10])
  df10 = df10.assign(count10_weight=[i[2] for i in result10])  

  df11 = pd.DataFrame()
  df11 = df11.assign(index=[i[0] for i in result11])
  df11 = df11.assign(count11=[i[1] for i in result11])
  df11 = df11.assign(count11_weight=[i[2] for i in result11])  

  df12= pd.DataFrame()
  df12 = df12.assign(index=[i[0] for i in result12])
  df12 = df12.assign(count12=[i[1] for i in result12])
  df12 = df12.assign(count12_weight=[i[2] for i in result12])  

  df13 = pd.DataFrame()
  df13 = df13.assign(index=[i[0] for i in result13])
  df13 = df13.assign(count13=[i[1] for i in result13])
  df13 = df13.assign(count13_weight=[i[2] for i in result13])  

  df14 = pd.DataFrame()
  df14 = df14.assign(index=[i[0] for i in result14])
  df14 = df14.assign(count14=[i[1] for i in result14])
  df14 = df14.assign(count14_weight=[i[2] for i in result14])  

  df15 = pd.DataFrame()
  df15 = df15.assign(index=[i[0] for i in result15])
  df15 = df15.assign(count15=[i[1] for i in result15])
  df15 = df15.assign(count15_weight=[i[2] for i in result15])  

  df0 = pd.merge(df,df0,on='index',how='left')
  df1 = pd.merge(df,df1,on='index',how='left')
  df2 = pd.merge(df,df2,on='index',how='left')
  df3 = pd.merge(df,df3,on='index',how='left')
  df4 = pd.merge(df,df4,on='index',how='left')
  df5 = pd.merge(df,df5,on='index',how='left')
  df6 = pd.merge(df,df6,on='index',how='left')
  df7 = pd.merge(df,df7,on='index',how='left')
  df8 = pd.merge(df,df8,on='index',how='left')
  df9 = pd.merge(df,df9,on='index',how='left')
  df10 = pd.merge(df,df10,on='index',how='left')
  df11 = pd.merge(df,df11,on='index',how='left')
  df12 = pd.merge(df,df12,on='index',how='left')
  df13 = pd.merge(df,df13,on='index',how='left')
  df14 = pd.merge(df,df14,on='index',how='left')
  df15 = pd.merge(df,df15,on='index',how='left')

  dfs = [df0, df1, df2, df3, df4, df5, df6,df7,df8,df9,df10,df11,df12,df13,df14,df15]

  df_final = reduce(lambda left,right: pd.merge(left,right,on='index'), dfs)

  print(df_final.isnull().sum())

  df_final.to_csv('fft-i3-test-less-'+str(j)+'.csv',index=False)

  print(df_final.head())

In [0]:
window(1)

3283000
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
      index      count0  count0_weight
0    1000.0  100.000000             62
1    2000.0  100.000000             62
2    3000.0    0.000000             84
3    4000.0  100.000000             45
4    5000.0  100.000000             92
5    6000.0  100.000000             53
6    7000.0    0.000000             67
7    8000.0  100.000000             97
8    9000.0    0.000000             85
9   10000.0  100.000000            130
10  11000.0    0.000000             77
11  12000.0  100.000000            114
12  13000.0  100.000000            129
13  14000.0    0.000000             94
14  15000.0   98.550725             69
index                0
count0             476
count0_weight      476
count1             431
count1_weight      431
count2             679
count2_weight      679
count3            1080
count3_weight     1080
count4             370
count4_weight      370
count5             325
count5_weight      325
count6             387
count6_weight      387
count7             600
count7_weight      600
count8             442
count8_weight      442
count9             356
count9_weight      356
count10            520
count10_weight     520
count11            469
count11_weight     469
count12            864
count12_weight     864
count13            672
count13_weight     672
count14            650
count14_weight     650
count15            570
count15_weight     570
dtype: int64
   index  count0  count0_weight  ...  count14_weight     count15  count15_weight
0   1000   100.0           62.0  ...            25.0  100.000000            63.0
1   2000   100.0           62.0  ...            42.0  100.000000            79.0
2   3000     0.0           84.0  ...            11.0    0.000000            50.0
3   4000   100.0           45.0  ...            25.0   91.071429            56.0
4   5000   100.0           92.0  ...            30.0  100.000000            85.0

[5 rows x 33 columns]

In [49]:
window(2)

3282000
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
      index      count0  count0_weight
0    1000.0    0.000000             62
1    2000.0    0.000000             61
2    3000.0    0.000000             85
3    4000.0    0.000000             44
4    5000.0  100.000000             94
5    6000.0  100.000000             51
6    7000.0    0.000000             69
7    8000.0  100.000000             97
8    9000.0    0.000000             81
9   10000.0  100.000000            136
10  11000.0   68.852459             61
11  12000.0  100.000000            122
12  13000.0  100.000000            122
13  14000.0    0.000000             98
14  15000.0  100.000000             71
index                0
count0             437
count0_weight      437
count1             401
count1_weight      401
count2             612
count2_weight      612
count3             915
count3_weight      915
count4             347
count4_weight      347
count5             257
count5_weight      257
count6             302
count6_weight      302
count7             364
count7_weight      364
count8             761
count8_weight      761
count9             407
count9_weight      407
count10            559
count10_weight     559
count11            505
count11_weight     505
count12           1598
count12_weight    1598
count13           1071
count13_weight    1071
count14            868
count14_weight     868
count15            691
count15_weight     691
dtype: int64
   index  count0  count0_weight  ...  count14_weight     count15  count15_weight
0   1000     0.0           62.0  ...            22.0  100.000000            61.0
1   2000     0.0           61.0  ...            39.0  100.000000            72.0
2   3000     0.0           85.0  ...             6.0   89.583333            48.0
3   4000     0.0           44.0  ...            22.0  100.000000            59.0
4   5000   100.0           94.0  ...            30.0  100.000000            86.0

[5 rows x 33 columns]

In [47]:
window(3)

3280000
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
      index     count0  count0_weight
0    1000.0    0.00000             61
1    2000.0    0.00000             59
2    3000.0  100.00000             84
3    4000.0    0.00000             42
4    5000.0  100.00000             93
5    6000.0  100.00000             51
6    7000.0    0.00000             68
7    8000.0  100.00000             93
8    9000.0   28.26087             92
9   10000.0  100.00000            119
10  11000.0    0.00000             73
11  12000.0  100.00000            115
12  13000.0    0.00000            122
13  14000.0    0.00000             93
14  15000.0  100.00000             63
index                0
count0             508
count0_weight      508
count1             575
count1_weight      575
count2             768
count2_weight      768
count3            1035
count3_weight     1035
count4             340
count4_weight      340
count5             365
count5_weight      365
count6             386
count6_weight      386
count7             514
count7_weight      514
count8             394
count8_weight      394
count9             279
count9_weight      279
count10            349
count10_weight     349
count11            268
count11_weight     268
count12            785
count12_weight     785
count13            654
count13_weight     654
count14            603
count14_weight     603
count15            536
count15_weight     536
dtype: int64
   index  count0  count0_weight  ...  count14_weight  count15  count15_weight
0   1000     0.0           61.0  ...            26.0      0.0            63.0
1   2000     0.0           59.0  ...            41.0    100.0            74.0
2   3000   100.0           84.0  ...            11.0    100.0            50.0
3   4000     0.0           42.0  ...            25.0    100.0            61.0
4   5000   100.0           93.0  ...            35.0    100.0            87.0

[5 rows x 33 columns]

In [45]:
window(4)

3280000
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
      index  count0  count0_weight
0    1000.0   100.0             61
1    2000.0   100.0             60
2    3000.0     0.0             82
3    4000.0     0.0             42
4    5000.0   100.0             87
5    6000.0   100.0             57
6    7000.0     0.0             71
7    8000.0   100.0             90
8    9000.0     0.0             84
9   10000.0   100.0            131
10  11000.0     0.0             63
11  12000.0   100.0            131
12  13000.0   100.0            109
13  14000.0   100.0             88
14  15000.0   100.0             67
index                0
count0             565
count0_weight      565
count1             634
count1_weight      634
count2             768
count2_weight      768
count3             994
count3_weight      994
count4             430
count4_weight      430
count5             383
count5_weight      383
count6             315
count6_weight      315
count7             367
count7_weight      367
count8             710
count8_weight      710
count9             347
count9_weight      347
count10            390
count10_weight     390
count11            321
count11_weight     321
count12           1651
count12_weight    1651
count13           1148
count13_weight    1148
count14            894
count14_weight     894
count15            691
count15_weight     691
dtype: int64
   index  count0  count0_weight  ...  count14_weight     count15  count15_weight
0   1000   100.0           61.0  ...            22.0    0.000000            61.0
1   2000   100.0           60.0  ...            39.0  100.000000            72.0
2   3000     0.0           82.0  ...             6.0   54.166667            48.0
3   4000     0.0           42.0  ...            22.0  100.000000            54.0
4   5000   100.0           87.0  ...            34.0  100.000000            92.0

[5 rows x 33 columns]

In [43]:
window(5)

3281000
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
      index      count0  count0_weight
0    1000.0    0.000000             61
1    2000.0    0.000000             59
2    3000.0  100.000000             84
3    4000.0    0.000000             42
4    5000.0  100.000000             93
5    6000.0  100.000000             51
6    7000.0    0.000000             67
7    8000.0    0.000000             95
8    9000.0   27.777778             90
9   10000.0  100.000000            121
10  11000.0    0.000000             69
11  12000.0  100.000000            118
12  13000.0    0.000000            122
13  14000.0    0.000000             93
14  15000.0   79.365079             63
index                0
count0             627
count0_weight      627
count1             708
count1_weight      708
count2             855
count2_weight      855
count3            1127
count3_weight     1127
count4             470
count4_weight      470
count5             478
count5_weight      478
count6             412
count6_weight      412
count7             502
count7_weight      502
count8             592
count8_weight      592
count9             499
count9_weight      499
count10            622
count10_weight     622
count11            568
count11_weight     568
count12            950
count12_weight     950
count13            848
count13_weight     848
count14            801
count14_weight     801
count15            720
count15_weight     720
dtype: int64
   index  count0  count0_weight  ...  count14_weight  count15  count15_weight
0   1000     0.0           61.0  ...            25.0      0.0            63.0
1   2000     0.0           59.0  ...            42.0    100.0            74.0
2   3000   100.0           84.0  ...            11.0     44.0            50.0
3   4000     0.0           42.0  ...            24.0      0.0            60.0
4   5000   100.0           93.0  ...            37.0    100.0            93.0

[5 rows x 33 columns]