<a href="https://colab.research.google.com/github/chamikasudusinghe/nocml/blob/master/fft_i2_other.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Module Imports for Data Fetiching and Visualization

In [0]:
import time
import pandas as pd
import numpy as np
import math
import pickle
from functools import reduce

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [49]:
from google.colab import drive
drive.mount('/content/drive')
root_dir = "/content/drive/My Drive/model-i2-less-features"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
root_rdx = "/content/drive/My Drive/radix"
root_lu = "/content/drive/My Drive/lu"
root_fmm = "/content/drive/My Drive/fmm"

In [0]:
from sklearn import preprocessing
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [0]:
import statsmodels.api as sm
from sklearn import metrics

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

Importing Dataset from GitHub

Test Data

In [0]:
df0_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r0.csv")
df0_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r0.csv")
df0_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r0.csv")
df0_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r0/4-fft-malicious-n-0-6-9-15-m-7-11-r0.csv?token=AKVFSOEPMNCCTKPNX4MNWYS64H3ZM')
df0_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r0/4-fft-malicious-n-0-6-9-15-m-7-12-r0.csv?token=AKVFSODEXN6OEHVKJDJWR3S64H3ZS')

In [0]:
df1_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r1.csv")
df1_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r1.csv")
df1_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r1.csv")
df1_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r1/4-fft-malicious-n-0-6-9-15-m-7-11-r1.csv?token=AKVFSOGXOKXCV4ZQWTTFUVC64H4AI')
df1_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r1/4-fft-malicious-n-0-6-9-15-m-7-12-r1.csv?token=AKVFSOECUNR2NOTT43OZCN264H4AS')

In [0]:
df2_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r2.csv")
df2_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r2.csv")
df2_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r2.csv")
df2_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r2/4-fft-malicious-n-0-6-9-15-m-7-11-r2.csv?token=AKVFSOEWGKQ3QQ6MYOHPL4264H6BU')
df2_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r2/4-fft-malicious-n-0-6-9-15-m-7-12-r2.csv?token=AKVFSOC322DAT7QDRMUHR2S64H6B2')

In [0]:
df3_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r3.csv")
df3_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r3.csv")
df3_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r3.csv")
df3_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r3/4-fft-malicious-n-0-6-9-15-m-7-11-r3.csv?token=AKVFSOHH76DGKR3NQE3P23264H6VS')
df3_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r3/4-fft-malicious-n-0-6-9-15-m-7-12-r3.csv?token=AKVFSOHISKBOPBTRWGSNTKC64H6V4')

In [0]:
df4_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r4.csv")
df4_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r4.csv")
df4_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r4.csv")
df4_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r4/4-fft-malicious-n-0-6-9-15-m-7-11-r4.csv?token=AKVFSOB7Q3BEIMGX3RTEYP264H7LA')
df4_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r4/4-fft-malicious-n-0-6-9-15-m-7-12-r4.csv?token=AKVFSOCTYHLY4LXMC262ITC64H7LG')

In [0]:
df5_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r5.csv")
df5_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r5.csv")
df5_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r5.csv")
df5_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r5/4-fft-malicious-n-0-6-9-15-m-7-11-r5.csv?token=AKVFSOFFFOCILTHOTTIP7XS64IAQO')
df5_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r5/4-fft-malicious-n-0-6-9-15-m-7-12-r5.csv?token=AKVFSOGGMXIXWZYZVZNUDD264IAQS')

In [0]:
df6_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r6.csv")
df6_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r6.csv")
df6_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r6.csv")
df6_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r6/4-fft-malicious-n-0-6-9-15-m-7-11-r6.csv?token=AKVFSOC43VEQFYVPAG6RWZC64IA7K')
df6_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r6/4-fft-malicious-n-0-6-9-15-m-7-12-r6.csv?token=AKVFSOBIVHJPJLC3NTFQUU264IA7S')

In [0]:
df7_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r7.csv")
df7_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r7.csv")
df7_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r7.csv")
df7_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r7/4-fft-malicious-n-0-6-9-15-m-7-11-r7.csv?token=AKVFSOFUPS2W5NLNPBCEI6C64IBMU')
df7_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r7/4-fft-malicious-n-0-6-9-15-m-7-12-r7.csv?token=AKVFSOBFSCGUOWEKU45GQJC64IBMY')

In [0]:
df8_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r8.csv")
df8_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r8.csv")
df8_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r8.csv")
df8_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r8/4-fft-malicious-n-0-6-9-15-m-7-11-r8.csv?token=AKVFSOGP5X53F3VNH24GAEC64IBZG')
df8_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r8/4-fft-malicious-n-0-6-9-15-m-7-12-r8.csv?token=AKVFSOFXUMXLCOZACXGY67S64IBZO')

In [0]:
df9_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r9.csv")
df9_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r9.csv")
df9_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r9.csv")
df9_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r9/4-fft-malicious-n-0-6-9-15-m-7-11-r9.csv?token=AKVFSOECRP4HXQX4ENUBQZC64ICPK')
df9_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r9/4-fft-malicious-n-0-6-9-15-m-7-12-r9.csv?token=AKVFSOE7BVO6CPCMR5SKKDC64ICPO')

In [0]:
df10_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r10.csv")
df10_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r10.csv")
df10_3 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r10/4-fft-malicious-n-0-6-9-15-m-11-12-r10.csv?token=AKVFSOC5GRVHDVGK4QBU7MS64IDLO')
df10_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r10/4-fft-malicious-n-0-6-9-15-m-7-11-r10.csv?token=AKVFSOGZ3FY6NUK67TUVDZ264IDLU')
df10_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r10/4-fft-malicious-n-0-6-9-15-m-7-12-r10.csv?token=AKVFSODYX7XNLDYEDSHMVV264IDLY')

In [0]:
df11_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r11.csv")
df11_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r11.csv")
df11_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r11.csv")
df11_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r11/4-fft-malicious-n-0-6-9-15-m-7-11-r11.csv?token=AKVFSOBMHE2VPWA7AV345VC64IETY')
df11_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r11/4-fft-malicious-n-0-6-9-15-m-7-12-r11.csv?token=AKVFSOB4W4XKIGMJZRLIAFC64IEUC')

In [0]:
df12_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r12.csv")
df12_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r12.csv")
df12_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r12.csv")
df12_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r12/4-fft-malicious-n-0-6-9-15-m-7-11-r12.csv?token=AKVFSOBTH4ZO5PWKGDY46GS64IE7K')
df12_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r12/4-fft-malicious-n-0-6-9-15-m-7-12-r12.csv?token=AKVFSOCNXJ4POVY3RMLEBO264IE7Q')

In [0]:
df13_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r13.csv")
df13_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r13.csv")
df13_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r13.csv")
df13_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r13/4-fft-malicious-n-0-6-9-15-m-7-11-r13.csv?token=AKVFSOEFJIGQF2P3577ZJYS64IFQW')
df13_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r13/4-fft-malicious-n-0-6-9-15-m-7-12-r13.csv?token=AKVFSOA5XKKUNVPBV7KCNMC64IFQ4')

In [0]:
df14_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r14.csv")
df14_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r14.csv")
df14_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r14.csv")
df14_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r14/4-fft-malicious-n-0-6-9-15-m-7-11-r14.csv?token=AKVFSOFONKMF3HDQAUQZIFS64IGK2')
df14_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r14/4-fft-malicious-n-0-6-9-15-m-7-12-r14.csv?token=AKVFSOA3QNMERJDLARYJZXK64IGLA')

In [0]:
df15_1 = pd.read_csv(root_rdx+"/2-radix-malicious-n-0-15-m-7-r15.csv")
df15_2 = pd.read_csv(root_fmm+"/2-fmm-malicious-n-0-15-m-7-r15.csv")
df15_3 = pd.read_csv(root_lu+"/2-lu-malicious-n-0-15-m-7-r15.csv")
df15_4 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r15/4-fft-malicious-n-0-6-9-15-m-7-11-r15.csv?token=AKVFSOBS6YMYZI4SLRNMMJ264IHUM')
df15_5 = pd.read_csv('https://raw.githubusercontent.com/chamikasudusinghe/nocml/master/dos%20results%20ver%204/iter-3/r15/4-fft-malicious-n-0-6-9-15-m-7-12-r15.csv?token=AKVFSOA57BNEABRLUAD7OLC64IHUQ')

In [111]:
print(df15_5.shape)
df15_5

(123780, 26)

        timestamp  outport  ...  vnet_vc_cc_index  target
0               7        3  ...                27       0
1              19        3  ...                27       0
2              98        0  ...               340       0
3              99        0  ...               340       0
4             100        0  ...               340       0
...           ...      ...  ...               ...     ...
123775    3280623        3  ...               165       0
123776    3280630        3  ...               165       0
123777    3280637        3  ...               165       0
123778    3280638        3  ...                36       0
123779    3280683        0  ...               189       0

[123780 rows x 26 columns]

In [0]:
def roundup(x):
  return int(math.ceil(x / 1000.0)) * 1000

In [0]:
def timecount(df):
    timearr = []
    interval = 999
    count = 0
    for index, row in df.iterrows():
        if row["timestamp"]<=interval :
            count+=1
        else:
            timearr.append([interval+1,count])
            count=1
            if (row["timestamp"] == roundup(row["timestamp"])):
              interval = row["timestamp"]+999
            else:
              interval = roundup(row["timestamp"])-1
    timearr.append([interval+1,count])
    return timearr

In [0]:
def standardize(df):
  test_X = df.drop(columns=['target','timestamp','src_ni','src_router','dst_ni','dst_router','inport','cache_coherence_type','flit_id','flit_type','vnet','current_hop','hop_percentage','port_index','cache_coherence_vnet_index','vnet_vc_cc_index'])
  test_Y = df['target']
  x = test_X.values
  min_max_scaler = preprocessing.MinMaxScaler()
  columns = test_X.columns
  x_scaled = min_max_scaler.fit_transform(x)
  test_X = pd.DataFrame(x_scaled)
  test_X.columns = columns
  print(test_X[test_X.duplicated()].shape)
  return test_X,test_Y

In [0]:
xgb_r0 = pickle.load(open(root_dir+"/xgbc-r0l.pickle.dat", "rb"))
xgb_r1 = pickle.load(open(root_dir+"/xgbc-r1l.pickle.dat", "rb"))
xgb_r2 = pickle.load(open(root_dir+"/xgbc-r2l.pickle.dat", "rb"))
xgb_r3 = pickle.load(open(root_dir+"/xgbc-r3l.pickle.dat", "rb"))
xgb_r4 = pickle.load(open(root_dir+"/xgbc-r4l.pickle.dat", "rb"))
xgb_r5 = pickle.load(open(root_dir+"/xgbc-r5l.pickle.dat", "rb"))
xgb_r6 = pickle.load(open(root_dir+"/xgbc-r6l.pickle.dat", "rb"))
xgb_r7 = pickle.load(open(root_dir+"/xgbc-r7l.pickle.dat", "rb"))
xgb_r8 = pickle.load(open(root_dir+"/xgbc-r8l.pickle.dat", "rb"))
xgb_r9 = pickle.load(open(root_dir+"/xgbc-r9l.pickle.dat", "rb"))
xgb_r10 = pickle.load(open(root_dir+"/xgbc-r10l.pickle.dat", "rb"))
xgb_r11 = pickle.load(open(root_dir+"/xgbc-r11l.pickle.dat", "rb"))
xgb_r12 = pickle.load(open(root_dir+"/xgbc-r12l.pickle.dat", "rb"))
xgb_r13 = pickle.load(open(root_dir+"/xgbc-r13l.pickle.dat", "rb"))
xgb_r14 = pickle.load(open(root_dir+"/xgbc-r14l.pickle.dat", "rb"))
xgb_r15 = pickle.load(open(root_dir+"/xgbc-r15l.pickle.dat", "rb"))

In [75]:
df0_1.shape

(101101, 26)

In [0]:
def window(j):

  timearr0 = timecount(df0_3)
  timearr1 = timecount(df1_3)
  timearr2 = timecount(df2_3)
  timearr3 = timecount(df3_3)
  timearr4 = timecount(df4_3)
  timearr5 = timecount(df5_3)
  timearr6 = timecount(df6_3)
  timearr7 = timecount(df7_3)
  timearr8 = timecount(df8_3)
  timearr9 = timecount(df9_3)
  timearr10 = timecount(df10_3)
  timearr11 = timecount(df11_3)
  timearr12 = timecount(df12_3)
  timearr13 = timecount(df13_3)
  timearr14 = timecount(df14_3)
  timearr15 = timecount(df15_3)

  max_limit = max(timearr0[-1],timearr1[-1],timearr2[-1],timearr3[-1],timearr4[-1],timearr5[-1],timearr6[-1],timearr7[-1],timearr8[-1],timearr9[-1],timearr10[-1],timearr11[-1],timearr12[-1],timearr13[-1],timearr14[-1],timearr15[-1])

  print(max_limit[0])
  
  def prediction(df,timearr,xgb):

    test_X,test_Y = standardize (df)
    counter = timearr[0][1]
    result = []
    begin = counter
    text_X0 = test_X[:counter]
    text_Y0 = test_Y[:counter]

    #try:
    #      kfold = KFold(n_splits=10, random_state=7, shuffle = True)
    #      results = cross_val_score(xgb, text_X0, text_Y0, cv=kfold)
    #      result.append([timearr[0][0],results.mean()*100,timearr[0][1]]) 
    #except:
    y_pred_xgbc_test= xgb.predict(text_X0)
    xgbc_score_test = accuracy_score(text_Y0,y_pred_xgbc_test)
    result.append([timearr[0][0],xgbc_score_test*100,timearr[0][1]]) 

    for i in range(1,len(timearr)):

      counter += timearr[i][1]

      text_X0 = test_X[begin:counter]
      text_Y0 = test_Y[begin:counter]

      #try:
      #    kfold = KFold(n_splits=10, random_state=7, shuffle = True)
      #    results = cross_val_score(xgb, text_X0, text_Y0, cv=kfold)
      #    result.append([timearr[i][0],results.mean()*100,timearr[i][1]]) 
      #except:
      y_pred_xgbc_test= xgb.predict(text_X0)
      xgbc_score_test = accuracy_score(text_Y0,y_pred_xgbc_test)
      result.append([timearr[i][0],xgbc_score_test*100,timearr[i][1]])

      begin = counter

    return result

  result0 = prediction(df0_3,timearr0,xgb_r0)
  result1 = prediction(df1_3,timearr1,xgb_r1)
  result2 = prediction(df2_3,timearr2,xgb_r2)
  result3 = prediction(df3_3,timearr3,xgb_r3)
  result4 = prediction(df4_3,timearr4,xgb_r4)
  result5 = prediction(df5_3,timearr5,xgb_r5)
  result6 = prediction(df6_3,timearr6,xgb_r6)
  result7 = prediction(df7_3,timearr7,xgb_r7)
  result8 = prediction(df8_3,timearr8,xgb_r8)
  result9 = prediction(df9_3,timearr9,xgb_r9)
  result10 = prediction(df10_3,timearr10,xgb_r10)
  result11 = prediction(df11_3,timearr11,xgb_r11)
  result12 = prediction(df12_3,timearr12,xgb_r12)
  result13 = prediction(df13_3,timearr13,xgb_r13)
  result14 = prediction(df14_3,timearr14,xgb_r14)
  result15 = prediction(df15_3,timearr15,xgb_r15)

  indexarr = []

  for i in range(1000,int(max_limit[0])+1,1000):
    indexarr.append(i)

  df = pd.DataFrame()
  df = df.assign(index=indexarr)

  df0 = pd.DataFrame()
  df0 = df0.assign(index=[i[0] for i in result0])
  df0 = df0.assign(count0=[i[1] for i in result0])
  df0 = df0.assign(count0_weight=[i[2] for i in result0])
  print(df0.head(15))

  df1 = pd.DataFrame()
  df1 = df1.assign(index=[i[0] for i in result1])
  df1 = df1.assign(count1=[i[1] for i in result1])
  df1 = df1.assign(count1_weight=[i[2] for i in result1])

  df2= pd.DataFrame()
  df2 = df2.assign(index=[i[0] for i in result2])
  df2 = df2.assign(count2=[i[1] for i in result2])
  df2 = df2.assign(count2_weight=[i[2] for i in result2])

  df3 = pd.DataFrame()
  df3 = df3.assign(index=[i[0] for i in result3])
  df3 = df3.assign(count3=[i[1] for i in result3])
  df3 = df3.assign(count3_weight=[i[2] for i in result3])  

  df4 = pd.DataFrame()
  df4 = df4.assign(index=[i[0] for i in result4])
  df4 = df4.assign(count4=[i[1] for i in result4])
  df4 = df4.assign(count4_weight=[i[2] for i in result4])  

  df5 = pd.DataFrame()
  df5 = df5.assign(index=[i[0] for i in result5])
  df5 = df5.assign(count5=[i[1] for i in result5])
  df5 = df5.assign(count5_weight=[i[2] for i in result5])  

  df6 = pd.DataFrame()
  df6 = df6.assign(index=[i[0] for i in result6])
  df6 = df6.assign(count6=[i[1] for i in result6])
  df6 = df6.assign(count6_weight=[i[2] for i in result6])  

  df7= pd.DataFrame()
  df7 = df7.assign(index=[i[0] for i in result7])
  df7 = df7.assign(count7=[i[1] for i in result7])
  df7 = df7.assign(count7_weight=[i[2] for i in result7])  

  df8 = pd.DataFrame()
  df8 = df8.assign(index=[i[0] for i in result8])
  df8 = df8.assign(count8=[i[1] for i in result8])
  df8 = df8.assign(count8_weight=[i[2] for i in result8])  

  df9 = pd.DataFrame()
  df9 = df9.assign(index=[i[0] for i in result9])
  df9 = df9.assign(count9=[i[1] for i in result9])
  df9 = df9.assign(count9_weight=[i[2] for i in result9])  

  df10 = pd.DataFrame()
  df10 = df10.assign(index=[i[0] for i in result10])
  df10 = df10.assign(count10=[i[1] for i in result10])
  df10 = df10.assign(count10_weight=[i[2] for i in result10])  

  df11 = pd.DataFrame()
  df11 = df11.assign(index=[i[0] for i in result11])
  df11 = df11.assign(count11=[i[1] for i in result11])
  df11 = df11.assign(count11_weight=[i[2] for i in result11])  

  df12= pd.DataFrame()
  df12 = df12.assign(index=[i[0] for i in result12])
  df12 = df12.assign(count12=[i[1] for i in result12])
  df12 = df12.assign(count12_weight=[i[2] for i in result12])  

  df13 = pd.DataFrame()
  df13 = df13.assign(index=[i[0] for i in result13])
  df13 = df13.assign(count13=[i[1] for i in result13])
  df13 = df13.assign(count13_weight=[i[2] for i in result13])  

  df14 = pd.DataFrame()
  df14 = df14.assign(index=[i[0] for i in result14])
  df14 = df14.assign(count14=[i[1] for i in result14])
  df14 = df14.assign(count14_weight=[i[2] for i in result14])  

  df15 = pd.DataFrame()
  df15 = df15.assign(index=[i[0] for i in result15])
  df15 = df15.assign(count15=[i[1] for i in result15])
  df15 = df15.assign(count15_weight=[i[2] for i in result15])  

  df0 = pd.merge(df,df0,on='index',how='left')
  df1 = pd.merge(df,df1,on='index',how='left')
  df2 = pd.merge(df,df2,on='index',how='left')
  df3 = pd.merge(df,df3,on='index',how='left')
  df4 = pd.merge(df,df4,on='index',how='left')
  df5 = pd.merge(df,df5,on='index',how='left')
  df6 = pd.merge(df,df6,on='index',how='left')
  df7 = pd.merge(df,df7,on='index',how='left')
  df8 = pd.merge(df,df8,on='index',how='left')
  df9 = pd.merge(df,df9,on='index',how='left')
  df10 = pd.merge(df,df10,on='index',how='left')
  df11 = pd.merge(df,df11,on='index',how='left')
  df12 = pd.merge(df,df12,on='index',how='left')
  df13 = pd.merge(df,df13,on='index',how='left')
  df14 = pd.merge(df,df14,on='index',how='left')
  df15 = pd.merge(df,df15,on='index',how='left')

  dfs = [df0, df1, df2, df3, df4, df5, df6,df7,df8,df9,df10,df11,df12,df13,df14,df15]

  df_final = reduce(lambda left,right: pd.merge(left,right,on='index'), dfs)

  print(df_final.isnull().sum())

  df_final.to_csv('fft-i3-test-less-'+str(j)+'.csv',index=False)

  print(df_final.head())

In [38]:
window(1)

10942000
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
      index      count0  count0_weight
0    1000.0  100.000000             68
1    2000.0   51.282051             78
2    3000.0   83.050847             59
3    4000.0  100.000000             42
4    5000.0    0.000000             58
5    6000.0    0.000000             65
6    7000.0   39.344262             61
7    8000.0   79.032258             62
8    9000.0   76.190476             63
9   10000.0    0.000000             80
10  11000.0  100.000000             94
11  12000.0    0.000000             63
12  13000.0  100.000000             84
13  14000.0  100.000000            101
14  15000.0  100.000000            149
index                0
count0            5255
count0_weight     5255
count1            6279
count1_weight     6279
count2            7095
count2_weight     7095
count3            7858
count3_weight     7858
count4            4881
count4_weight     4881
count5            5565
count5_weight     5565
count6            5123
count6_weight     5123
count7            4481
count7_weight     4481
count8            6679
count8_weight     6679
count9            6399
count9_weight     6399
count10           6394
count10_weight    6394
count11           5021
count11_weight    5021
count12           8776
count12_weight    8776
count13           7614
count13_weight    7614
count14           6699
count14_weight    6699
count15           5507
count15_weight    5507
dtype: int64
   index      count0  count0_weight  ...  count14_weight  count15  count15_weight
0   1000  100.000000           68.0  ...            16.0    100.0            59.0
1   2000   51.282051           78.0  ...            16.0      0.0            74.0
2   3000   83.050847           59.0  ...            12.0    100.0            71.0
3   4000  100.000000           42.0  ...            22.0      0.0            54.0
4   5000    0.000000           58.0  ...            19.0     87.5            56.0

[5 rows x 33 columns]

In [77]:
window(2)

1901000
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
      index      count0  count0_weight
0    1000.0  100.000000             53
1    2000.0   94.117647             51
2    3000.0   95.588235             68
3    4000.0    0.000000             51
4    5000.0   30.000000             60
5    6000.0    3.389831             59
6    7000.0    0.000000             70
7    8000.0    0.000000             69
8    9000.0  100.000000             58
9   10000.0    0.000000             66
10  11000.0    0.000000             73
11  12000.0   96.250000             80
12  13000.0   40.322581             62
13  14000.0   16.216216             74
14  15000.0   86.363636             88
index               0
count0             35
count0_weight      35
count1             85
count1_weight      85
count2            200
count2_weight     200
count3            343
count3_weight     343
count4             18
count4_weight      18
count5             40
count5_weight      40
count6             35
count6_weight      35
count7             19
count7_weight      19
count8             78
count8_weight      78
count9             66
count9_weight      66
count10            61
count10_weight     61
count11            15
count11_weight     15
count12           426
count12_weight    426
count13           177
count13_weight    177
count14            72
count14_weight     72
count15            32
count15_weight     32
dtype: int64
   index      count0  count0_weight  ...  count14_weight     count15  count15_weight
0   1000  100.000000           53.0  ...            11.0  100.000000            65.0
1   2000   94.117647           51.0  ...            30.0  100.000000            73.0
2   3000   95.588235           68.0  ...            15.0    0.000000            65.0
3   4000    0.000000           51.0  ...             9.0  100.000000            46.0
4   5000   30.000000           60.0  ...            10.0    2.040816            49.0

[5 rows x 33 columns]

In [113]:
window(3)

5761000
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
      index      count0  count0_weight
0    1000.0  100.000000             63
1    2000.0    0.000000             60
2    3000.0   16.949153             59
3    4000.0    0.000000             48
4    5000.0   93.442623             61
5    6000.0   22.535211             71
6    7000.0  100.000000             65
7    8000.0   73.770492             61
8    9000.0    0.000000             72
9   10000.0   93.442623             61
10  11000.0    0.000000             70
11  12000.0  100.000000             98
12  13000.0  100.000000             91
13  14000.0    0.000000             69
14  15000.0    1.449275             69
index                0
count0            1473
count0_weight     1473
count1            1975
count1_weight     1975
count2            2400
count2_weight     2400
count3            2842
count3_weight     2842
count4            1334
count4_weight     1334
count5            1649
count5_weight     1649
count6            1386
count6_weight     1386
count7            1108
count7_weight     1108
count8            2328
count8_weight     2328
count9            2036
count9_weight     2036
count10           2830
count10_weight    2830
count11           1323
count11_weight    1323
count12           3476
count12_weight    3476
count13           2723
count13_weight    2723
count14           2173
count14_weight    2173
count15           1526
count15_weight    1526
dtype: int64
   index      count0  count0_weight  ...  count14_weight     count15  count15_weight
0   1000  100.000000           63.0  ...            18.0  100.000000            60.0
1   2000    0.000000           60.0  ...            17.0  100.000000            64.0
2   3000   16.949153           59.0  ...            31.0  100.000000            68.0
3   4000    0.000000           48.0  ...            37.0   95.774648            71.0
4   5000   93.442623           61.0  ...            47.0    0.000000            76.0

[5 rows x 33 columns]

In [0]:
window(4)

3280000
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
      index  count0  count0_weight
0    1000.0   100.0             61
1    2000.0   100.0             60
2    3000.0     0.0             82
3    4000.0     0.0             42
4    5000.0   100.0             87
5    6000.0   100.0             57
6    7000.0     0.0             71
7    8000.0   100.0             90
8    9000.0     0.0             84
9   10000.0   100.0            131
10  11000.0     0.0             63
11  12000.0   100.0            131
12  13000.0   100.0            109
13  14000.0   100.0             88
14  15000.0   100.0             67
index                0
count0             565
count0_weight      565
count1             634
count1_weight      634
count2             768
count2_weight      768
count3             994
count3_weight      994
count4             430
count4_weight      430
count5             383
count5_weight      383
count6             315
count6_weight      315
count7             367
count7_weight      367
count8             710
count8_weight      710
count9             347
count9_weight      347
count10            390
count10_weight     390
count11            321
count11_weight     321
count12           1651
count12_weight    1651
count13           1148
count13_weight    1148
count14            894
count14_weight     894
count15            691
count15_weight     691
dtype: int64
   index  count0  count0_weight  ...  count14_weight     count15  count15_weight
0   1000   100.0           61.0  ...            22.0    0.000000            61.0
1   2000   100.0           60.0  ...            39.0  100.000000            72.0
2   3000     0.0           82.0  ...             6.0   54.166667            48.0
3   4000     0.0           42.0  ...            22.0  100.000000            54.0
4   5000   100.0           87.0  ...            34.0  100.000000            92.0

[5 rows x 33 columns]

In [0]:
window(5)

3281000
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
(0, 10)
      index      count0  count0_weight
0    1000.0    0.000000             61
1    2000.0    0.000000             59
2    3000.0  100.000000             84
3    4000.0    0.000000             42
4    5000.0  100.000000             93
5    6000.0  100.000000             51
6    7000.0    0.000000             67
7    8000.0    0.000000             95
8    9000.0   27.777778             90
9   10000.0  100.000000            121
10  11000.0    0.000000             69
11  12000.0  100.000000            118
12  13000.0    0.000000            122
13  14000.0    0.000000             93
14  15000.0   79.365079             63
index                0
count0             627
count0_weight      627
count1             708
count1_weight      708
count2             855
count2_weight      855
count3            1127
count3_weight     1127
count4             470
count4_weight      470
count5             478
count5_weight      478
count6             412
count6_weight      412
count7             502
count7_weight      502
count8             592
count8_weight      592
count9             499
count9_weight      499
count10            622
count10_weight     622
count11            568
count11_weight     568
count12            950
count12_weight     950
count13            848
count13_weight     848
count14            801
count14_weight     801
count15            720
count15_weight     720
dtype: int64
   index  count0  count0_weight  ...  count14_weight  count15  count15_weight
0   1000     0.0           61.0  ...            25.0      0.0            63.0
1   2000     0.0           59.0  ...            42.0    100.0            74.0
2   3000   100.0           84.0  ...            11.0     44.0            50.0
3   4000     0.0           42.0  ...            24.0      0.0            60.0
4   5000   100.0           93.0  ...            37.0    100.0            93.0

[5 rows x 33 columns]