In [13]:
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df = pd.read_csv('wat-good.csv')
df = df.loc[df['router'] == 1]
df = df.drop(columns=['router'])
df.to_csv('wat-r1-good.csv',index=False)

In [15]:
df = pd.read_csv('wat-r1-good.csv')
df

,time,outport,inport,packet_address,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,dst_ni,dst_router,enq_time,pkt_chuck,pkt_count_all,pkt_max_all,target
0,11,2,4,0x1dc0,0,0,3,2,8,0,0,23,7,3,0,25,26,1
1,83,4,2,0x1dc0,3,0,0,4,16,18,2,0,0,74,0,12,26,1
2,84,4,2,0x1dc0,3,1,1,4,16,18,2,0,0,74,0,11,26,1
3,85,4,2,0x1dc0,3,2,1,4,16,18,2,0,0,74,0,10,26,1
4,86,4,2,0x1dc0,3,3,1,4,16,18,2,0,0,74,0,9,26,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50107,3251376,2,4,0x1152c0,4,1,1,2,8,0,0,27,11,3251361,10026,22,26,1
50108,3251383,2,4,0x1152c0,4,2,1,2,8,0,0,27,11,3251361,10026,17,26,1
50109,3251390,2,4,0x1152c0,4,3,1,2,8,0,0,27,11,3251361,10026,11,26,1
50110,3251397,2,4,0x1152c0,4,4,2,2,8,0,0,27,11,3251361,10026,4,26,1
50111,3251398,2,4,0x4d2c0,0,0,3,2,9,0,0,27,11,3251362,10027,3,26,1

In [16]:
timearr = []
interval = 99
count = 0
for index, row in df.iterrows():
    if row["time"]<=interval:
        count+=1
    else:
        timearr.append([interval+1,count])
        count=1
        interval+=100
timearr.append([interval+1,count])

In [17]:
countarr = []
maxarr = []
for i in range(len(timearr)):
    for cnt in range(timearr[i][1],0,-1):
        countarr.append(cnt)
        maxarr.append(timearr[i][1])
print(len(countarr))

50112

In [18]:
df = df.assign(pkt_count=countarr)
df = df.assign(pkt_max=maxarr)

In [19]:
df

,time,outport,inport,packet_address,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,dst_ni,dst_router,enq_time,pkt_chuck,pkt_count_all,pkt_max_all,target,pkt_count,pkt_max
0,11,2,4,0x1dc0,0,0,3,2,8,0,0,23,7,3,0,25,26,1,6,6
1,83,4,2,0x1dc0,3,0,0,4,16,18,2,0,0,74,0,12,26,1,5,6
2,84,4,2,0x1dc0,3,1,1,4,16,18,2,0,0,74,0,11,26,1,4,6
3,85,4,2,0x1dc0,3,2,1,4,16,18,2,0,0,74,0,10,26,1,3,6
4,86,4,2,0x1dc0,3,3,1,4,16,18,2,0,0,74,0,9,26,1,2,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50107,3251376,2,4,0x1152c0,4,1,1,2,8,0,0,27,11,3251361,10026,22,26,1,5,6
50108,3251383,2,4,0x1152c0,4,2,1,2,8,0,0,27,11,3251361,10026,17,26,1,4,6
50109,3251390,2,4,0x1152c0,4,3,1,2,8,0,0,27,11,3251361,10026,11,26,1,3,6
50110,3251397,2,4,0x1152c0,4,4,2,2,8,0,0,27,11,3251361,10026,4,26,1,2,6
50111,3251398,2,4,0x4d2c0,0,0,3,2,9,0,0,27,11,3251362,10027,3,26,1,1,6

In [20]:
cols = list(df.columns)
a, b = cols.index('target'), cols.index('pkt_count')
cols[b], cols[a] = cols[a], cols[b]
df = df[cols]
df
cols = list(df.columns)
a, b = cols.index('target'), cols.index('pkt_max')
cols[b], cols[a] = cols[a], cols[b]
df = df[cols]
df

,time,outport,inport,packet_address,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,dst_ni,dst_router,enq_time,pkt_chuck,pkt_count_all,pkt_max_all,pkt_count,pkt_max,target
0,11,2,4,0x1dc0,0,0,3,2,8,0,0,23,7,3,0,25,26,6,6,1
1,83,4,2,0x1dc0,3,0,0,4,16,18,2,0,0,74,0,12,26,5,6,1
2,84,4,2,0x1dc0,3,1,1,4,16,18,2,0,0,74,0,11,26,4,6,1
3,85,4,2,0x1dc0,3,2,1,4,16,18,2,0,0,74,0,10,26,3,6,1
4,86,4,2,0x1dc0,3,3,1,4,16,18,2,0,0,74,0,9,26,2,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50107,3251376,2,4,0x1152c0,4,1,1,2,8,0,0,27,11,3251361,10026,22,26,5,6,1
50108,3251383,2,4,0x1152c0,4,2,1,2,8,0,0,27,11,3251361,10026,17,26,4,6,1
50109,3251390,2,4,0x1152c0,4,3,1,2,8,0,0,27,11,3251361,10026,11,26,3,6,1
50110,3251397,2,4,0x1152c0,4,4,2,2,8,0,0,27,11,3251361,10026,4,26,2,6,1
50111,3251398,2,4,0x4d2c0,0,0,3,2,9,0,0,27,11,3251362,10027,3,26,1,6,1

In [21]:
df.to_csv('wat-r1-good.csv',index=False)