In [10]:
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df = pd.read_csv('wat-mals.csv')
df = df.loc[df['router'] == 1]
df = df.drop(columns=['router'])
df.to_csv('wat-r1-mals.csv',index=False)

In [12]:
df = pd.read_csv('wat-r1-mals.csv')
df

,time,outport,inport,packet_address,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,dst_ni,dst_router,enq_time,pkt_chuck,pkt_count_all,pkt_max_all,target
0,7,2,0,0xeddc0,0,0,3,2,8,1,1,23,7,3,1,31,32,0
1,11,2,4,0x1dc0,0,0,3,2,8,0,0,23,7,3,0,29,32,0
2,79,0,2,0xeddc0,3,0,0,4,16,18,2,1,1,70,1,11,32,0
3,80,0,2,0xeddc0,3,1,1,4,16,18,2,1,1,70,1,10,32,0
4,81,0,2,0xeddc0,3,2,1,4,16,18,2,1,1,70,1,9,32,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71836,2022096,4,0,0x222700,4,1,1,2,10,1,1,28,12,2022085,11082,2,3,0
71837,2022103,4,0,0x222700,4,2,1,2,10,1,1,28,12,2022085,11082,45,47,0
71838,2022110,4,0,0x222700,4,3,1,2,10,1,1,28,12,2022085,11082,40,47,0
71839,2022117,4,0,0x222700,4,4,2,2,10,1,1,28,12,2022085,11082,35,47,0
71840,2022118,4,0,0x22e700,0,0,3,2,11,1,1,28,12,2022086,11083,33,47,0

In [13]:
timearr = []
interval = 99
count = 0
for index, row in df.iterrows():
    if row["time"]<=interval:
        count+=1
    else:
        timearr.append([interval+1,count])
        count=1
        interval+=100
timearr.append([interval+1,count])

In [14]:
countarr = []
maxarr = []
for i in range(len(timearr)):
    for cnt in range(timearr[i][1],0,-1):
        countarr.append(cnt)
        maxarr.append(timearr[i][1])
print(len(countarr))

71841

In [15]:
df = df.assign(pkt_count=countarr)
df = df.assign(pkt_max=maxarr)

In [16]:
df

,time,outport,inport,packet_address,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,dst_ni,dst_router,enq_time,pkt_chuck,pkt_count_all,pkt_max_all,target,pkt_count,pkt_max
0,7,2,0,0xeddc0,0,0,3,2,8,1,1,23,7,3,1,31,32,0,7,7
1,11,2,4,0x1dc0,0,0,3,2,8,0,0,23,7,3,0,29,32,0,6,7
2,79,0,2,0xeddc0,3,0,0,4,16,18,2,1,1,70,1,11,32,0,5,7
3,80,0,2,0xeddc0,3,1,1,4,16,18,2,1,1,70,1,10,32,0,4,7
4,81,0,2,0xeddc0,3,2,1,4,16,18,2,1,1,70,1,9,32,0,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71836,2022096,4,0,0x222700,4,1,1,2,10,1,1,28,12,2022085,11082,2,3,0,1,1
71837,2022103,4,0,0x222700,4,2,1,2,10,1,1,28,12,2022085,11082,45,47,0,1,1
71838,2022110,4,0,0x222700,4,3,1,2,10,1,1,28,12,2022085,11082,40,47,0,1,1
71839,2022117,4,0,0x222700,4,4,2,2,10,1,1,28,12,2022085,11082,35,47,0,1,1
71840,2022118,4,0,0x22e700,0,0,3,2,11,1,1,28,12,2022086,11083,33,47,0,1,1

In [17]:
cols = list(df.columns)
a, b = cols.index('target'), cols.index('pkt_count')
cols[b], cols[a] = cols[a], cols[b]
df = df[cols]
df
cols = list(df.columns)
a, b = cols.index('target'), cols.index('pkt_max')
cols[b], cols[a] = cols[a], cols[b]
df = df[cols]
df

,time,outport,inport,packet_address,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,dst_ni,dst_router,enq_time,pkt_chuck,pkt_count_all,pkt_max_all,pkt_count,pkt_max,target
0,7,2,0,0xeddc0,0,0,3,2,8,1,1,23,7,3,1,31,32,7,7,0
1,11,2,4,0x1dc0,0,0,3,2,8,0,0,23,7,3,0,29,32,6,7,0
2,79,0,2,0xeddc0,3,0,0,4,16,18,2,1,1,70,1,11,32,5,7,0
3,80,0,2,0xeddc0,3,1,1,4,16,18,2,1,1,70,1,10,32,4,7,0
4,81,0,2,0xeddc0,3,2,1,4,16,18,2,1,1,70,1,9,32,3,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71836,2022096,4,0,0x222700,4,1,1,2,10,1,1,28,12,2022085,11082,2,3,1,1,0
71837,2022103,4,0,0x222700,4,2,1,2,10,1,1,28,12,2022085,11082,45,47,1,1,0
71838,2022110,4,0,0x222700,4,3,1,2,10,1,1,28,12,2022085,11082,40,47,1,1,0
71839,2022117,4,0,0x222700,4,4,2,2,10,1,1,28,12,2022085,11082,35,47,1,1,0
71840,2022118,4,0,0x22e700,0,0,3,2,11,1,1,28,12,2022086,11083,33,47,1,1,0

In [18]:
df.to_csv('wat-r1-mals.csv',index=False)