In [13]:
import pandas as pd

In [14]:
df = pd.read_csv('wat-good.csv')
df = df.loc[df['router'] == 1]
df = df.drop(columns=['router'])
df.to_csv('wat-r1-good.csv',index=False)

In [15]:
df = pd.read_csv('wat-r1-good.csv')
df

,time,outport,inport,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,dst_ni,dst_router,pkt_chuck,hop_count,current_hop,hop_percentage,waiting_time
0,11,2,4,0,0,3,2,8,0,0,23,7,0,4,1,0.250000,8
1,83,4,2,3,0,0,4,16,18,2,0,0,0,2,1,0.500000,9
2,84,4,2,3,1,1,4,16,18,2,0,0,0,2,1,0.500000,10
3,85,4,2,3,2,1,4,16,18,2,0,0,0,2,1,0.500000,11
4,86,4,2,3,3,1,4,16,18,2,0,0,0,2,1,0.500000,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50096,3251158,2,4,4,1,1,2,8,0,0,22,6,10024,3,1,0.333333,15
50097,3251165,2,4,4,2,1,2,8,0,0,22,6,10024,3,1,0.333333,22
50098,3251172,2,4,4,3,1,2,8,0,0,22,6,10024,3,1,0.333333,29
50099,3251179,2,4,4,4,2,2,8,0,0,22,6,10024,3,1,0.333333,36
50100,3251180,2,4,0,0,3,2,9,0,0,22,6,10025,3,1,0.333333,36

In [16]:
timearr = []
interval = 99
count = 0
for index, row in df.iterrows():
    if row["time"]<=interval:
        count+=1
    else:
        timearr.append([interval+1,count])
        count=1
        interval+=100
timearr.append([interval+1,count])

In [17]:
countarr = []
increarr = []
maxarr = []
for i in range(len(timearr)):
    for cnt in range(timearr[i][1],0,-1):
        countarr.append(cnt)
        maxarr.append(timearr[i][1])
        increment = timearr[i][1] - cnt + 1
        increarr.append(increment)
print(len(countarr))

50101

In [18]:
df = df.assign(pkt_count=countarr)
df = df.assign(pkt_count_inc=increarr)
df = df.assign(pkt_max=maxarr)
df["counting_index_pos"] = df["pkt_count"]*df["pkt_count_inc"]
df["counting_index_100"] = df["counting_index_pos"]*df["pkt_max"]
df.head(50)

,time,outport,inport,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,...,pkt_chuck,hop_count,current_hop,hop_percentage,waiting_time,pkt_count,pkt_count_inc,pkt_max,counting_index_pos,counting_index_100
0,11,2,4,0,0,3,2,8,0,0,...,0,4,1,0.250000,8,6,1,6,6,36
1,83,4,2,3,0,0,4,16,18,2,...,0,2,1,0.500000,9,5,2,6,10,60
2,84,4,2,3,1,1,4,16,18,2,...,0,2,1,0.500000,10,4,3,6,12,72
3,85,4,2,3,2,1,4,16,18,2,...,0,2,1,0.500000,11,3,4,6,12,72
4,86,4,2,3,3,1,4,16,18,2,...,0,2,1,0.500000,12,2,5,6,10,60
5,90,4,2,3,4,2,4,16,18,2,...,0,2,1,0.500000,16,1,6,6,6,36
6,241,2,4,0,0,3,2,8,0,0,...,2,3,1,0.333333,8,1,1,1,1,1
7,302,4,2,3,0,0,4,16,18,2,...,2,2,1,0.500000,8,1,1,1,1,1
8,303,4,2,3,1,1,4,16,18,2,...,2,2,1,0.500000,9,5,1,5,5,25
9,304,4,2,3,2,1,4,16,18,2,...,2,2,1,0.500000,10,4,2,5,8,40
10,306,4,2,3,3,1,4,16,18,2,...,2,2,1,0.500000,12,3,3,5,9,45
11,309,4,2,3,4,2,4,16,18,2,...,2,2,1,0.500000,15,2,4,5,8,40
12,352,2,4,0,0,3,2,8,0,0,...,3,4,1,0.250000,8,1,5,5,5,25
13,421,4,2,3,0,0,4,16,18,2,...,3,2,1,0.500000,9,6,1,6,6,36
14,422,4,2,3,1,1,4,16,18,2,...,3,2,1,0.500000,10,5,2,6,10,60
15,423,4,2,3,2,1,4,16,18,2,...,3,2,1,0.500000,11,4,3,6,12,72
16,424,4,2,3,3,1,4,16,18,2,...,3,2,1,0.500000,12,3,4,6,12,72
17,428,4,2,3,4,2,4,16,18,2,...,3,2,1,0.500000,16,2,5,6,10,60
18,459,1,4,0,0,3,2,8,0,0,...,4,2,1,0.500000,8,1,6,6,6,36
19,520,1,2,2,0,3,2,8,18,2,...,4,2,1,0.500000,8,7,1,7,7,49
20,521,4,2,3,0,0,4,16,18,2,...,4,2,1,0.500000,9,6,2,7,12,84
21,522,4,2,3,1,1,4,16,18,2,...,4,2,1,0.500000,10,5,3,7,15,105
22,523,4,2,3,2,1,4,16,18,2,...,4,2,1,0.500000,11,4,4,7,16,112
23,524,4,2,3,3,1,4,16,18,2,...,4,2,1,0.500000,12,3,5,7,15,105
24,528,4,2,3,4,2,4,16,18,2,...,4,2,1,0.500000,16,2,6,7,12,84
25,561,0,4,0,0,3,2,8,0,0,...,5,1,1,1.000000,8,1,7,7,7,49
26,600,4,0,3,0,0,4,16,17,1,...,5,1,0,0.000000,4,9,1,9,9,81
27,601,4,0,3,1,1,4,16,17,1,...,5,1,0,0.000000,5,8,2,9,16,144
28,602,4,0,3,2,1,4,16,17,1,...,5,1,0,0.000000,6,7,3,9,21,189
29,603,4,0,3,3,1,4,16,17,1,...,5,1,0,0.000000,7,6,4,9,24,216
30,607,4,0,3,4,2,4,16,17,1,...,5,1,0,0.000000,11,5,5,9,25,225
31,628,2,4,0,0,3,2,8,0,0,...,6,4,1,0.250000,8,4,6,9,24,216
32,696,4,2,3,0,0,4,16,18,2,...,6,2,1,0.500000,8,3,7,9,21,189
33,697,4,2,3,1,1,4,16,18,2,...,6,2,1,0.500000,9,2,8,9,16,144
34,698,4,2,3,2,1,4,16,18,2,...,6,2,1,0.500000,10,1,9,9,9,81
35,700,4,2,3,3,1,4,16,18,2,...,6,2,1,0.500000,12,8,1,8,8,64
36,703,4,2,3,4,2,4,16,18,2,...,6,2,1,0.500000,15,7,2,8,14,112
37,722,0,4,0,0,3,2,8,0,0,...,7,1,1,1.000000,8,6,3,8,18,144
38,758,4,0,3,0,0,4,17,17,1,...,7,1,0,0.000000,4,5,4,8,20,160
39,759,4,0,3,1,1,4,17,17,1,...,7,1,0,0.000000,5,4,5,8,20,160
40,760,4,0,3,2,1,4,17,17,1,...,7,1,0,0.000000,6,3,6,8,18,144
41,761,4,0,3,3,1,4,17,17,1,...,7,1,0,0.000000,7,2,7,8,14,112
42,765,4,0,3,4,2,4,17,17,1,...,7,1,0,0.000000,11,1,8,8,8,64
43,808,2,4,0,0,3,2,8,0,0,...,8,5,1,0.200000,8,1,1,1,1,1
44,908,2,4,0,0,3,2,8,0,0,...,9,5,1,0.200000,8,1,1,1,1,1
45,1026,1,4,0,0,3,2,8,0,0,...,10,3,1,0.333333,8,1,1,1,1,1
46,1188,4,2,2,0,3,2,8,18,2,...,11,3,1,0.333333,8,6,1,6,6,36
47,1189,4,2,3,0,0,4,16,18,2,...,11,2,1,0.500000,9,5,2,6,10,60
48,1190,4,2,3,1,1,4,16,18,2,...,11,2,1,0.500000,10,4,3,6,12,72
49,1191,4,2,3,2,1,4,16,18,2,...,11,2,1,0.500000,11,3,4,6,12,72

In [19]:
#df["packet_types"] = df["packet_type"]
#df=pd.get_dummies(df, prefix=['outport', 'inport', 'packet_type'], columns=['outport', 'inport','packet_type'])

In [20]:
df.dtypes

time                    int64
outport                 int64
inport                  int64
packet_type             int64
flit_id                 int64
flit_type               int64
vnet                    int64
vc                      int64
src_ni                  int64
src_router              int64
dst_ni                  int64
dst_router              int64
pkt_chuck               int64
hop_count               int64
current_hop             int64
hop_percentage        float64
waiting_time            int64
pkt_count               int64
pkt_count_inc           int64
pkt_max                 int64
counting_index_pos      int64
counting_index_100      int64
dtype: object

In [21]:
#df['inport_1'] = 0
#df['inport_3'] = 0
#df['outport_3'] = 0

In [22]:
df['target'] = 1
df

,time,outport,inport,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,...,hop_count,current_hop,hop_percentage,waiting_time,pkt_count,pkt_count_inc,pkt_max,counting_index_pos,counting_index_100,target
0,11,2,4,0,0,3,2,8,0,0,...,4,1,0.250000,8,6,1,6,6,36,1
1,83,4,2,3,0,0,4,16,18,2,...,2,1,0.500000,9,5,2,6,10,60,1
2,84,4,2,3,1,1,4,16,18,2,...,2,1,0.500000,10,4,3,6,12,72,1
3,85,4,2,3,2,1,4,16,18,2,...,2,1,0.500000,11,3,4,6,12,72,1
4,86,4,2,3,3,1,4,16,18,2,...,2,1,0.500000,12,2,5,6,10,60,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50096,3251158,2,4,4,1,1,2,8,0,0,...,3,1,0.333333,15,5,8,12,40,480,1
50097,3251165,2,4,4,2,1,2,8,0,0,...,3,1,0.333333,22,4,9,12,36,432,1
50098,3251172,2,4,4,3,1,2,8,0,0,...,3,1,0.333333,29,3,10,12,30,360,1
50099,3251179,2,4,4,4,2,2,8,0,0,...,3,1,0.333333,36,2,11,12,22,264,1
50100,3251180,2,4,0,0,3,2,9,0,0,...,3,1,0.333333,36,1,12,12,12,144,1

In [23]:
df.to_csv('wat-r1-good.csv',index=False)