In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('wat-mal.csv')
df = df.loc[df['router'] == 1]
df = df.drop(columns=['router'])
df.to_csv('wat-r1-mal.csv',index=False)

In [22]:
df = pd.read_csv('wat-r1-mal.csv')
df

,time,outport,inport,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,dst_ni,dst_router,pkt_chuck,hop_count,current_hop,hop_percentage,waiting_time
0,7,2,0,0,0,3,2,8,1,1,23,7,1,3,0,0.00,4
1,11,2,4,0,0,3,2,8,0,0,23,7,0,4,1,0.25,8
2,79,0,2,3,0,0,4,16,18,2,1,1,1,1,1,1.00,9
3,80,0,2,3,1,1,4,16,18,2,1,1,1,1,1,1.00,10
4,81,0,2,3,2,1,4,16,18,2,1,1,1,1,1,1.00,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71836,2022096,4,0,4,1,1,2,10,1,1,28,12,11082,5,0,0.00,11
71837,2022103,4,0,4,2,1,2,10,1,1,28,12,11082,5,0,0.00,18
71838,2022110,4,0,4,3,1,2,10,1,1,28,12,11082,5,0,0.00,25
71839,2022117,4,0,4,4,2,2,10,1,1,28,12,11082,5,0,0.00,32
71840,2022118,4,0,0,0,3,2,11,1,1,28,12,11083,5,0,0.00,32

In [23]:
timearr = []
interval = 99
count = 0
for index, row in df.iterrows():
    if row["time"]<=interval:
        count+=1
    else:
        timearr.append([interval+1,count])
        count=1
        interval+=100
timearr.append([interval+1,count])

In [24]:
countarr = []
increarr = []
maxarr = []
for i in range(len(timearr)):
    for cnt in range(timearr[i][1],0,-1):
        countarr.append(cnt)
        maxarr.append(timearr[i][1])
        increment = timearr[i][1] - cnt + 1
        increarr.append(increment)
print(len(countarr))

71841

In [25]:
df = df.assign(pkt_count=countarr)
df = df.assign(pkt_count_inc=increarr)
df = df.assign(pkt_max=maxarr)
df["counting_index_pos"] = df["pkt_count"]*df["pkt_count_inc"]
df["counting_index_100"] = df["counting_index_pos"]*df["pkt_max"]
df.head(50)

,time,outport,inport,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,...,pkt_chuck,hop_count,current_hop,hop_percentage,waiting_time,pkt_count,pkt_count_inc,pkt_max,counting_index_pos,counting_index_100
0,7,2,0,0,0,3,2,8,1,1,...,1,3,0,0.000000,4,7,1,7,7,49
1,11,2,4,0,0,3,2,8,0,0,...,0,4,1,0.250000,8,6,2,7,12,84
2,79,0,2,3,0,0,4,16,18,2,...,1,1,1,1.000000,9,5,3,7,15,105
3,80,0,2,3,1,1,4,16,18,2,...,1,1,1,1.000000,10,4,4,7,16,112
4,81,0,2,3,2,1,4,16,18,2,...,1,1,1,1.000000,11,3,5,7,15,105
5,82,0,2,3,3,1,4,16,18,2,...,1,1,1,1.000000,12,2,6,7,12,84
6,86,0,2,3,4,2,4,16,18,2,...,1,1,1,1.000000,16,1,7,7,7,49
7,100,4,2,3,0,0,4,16,18,2,...,0,2,1,0.500000,8,11,1,11,11,121
8,101,4,0,0,0,3,2,9,1,1,...,2,3,0,0.000000,4,10,2,11,20,220
9,102,4,2,3,1,1,4,16,18,2,...,0,2,1,0.500000,10,9,3,11,27,297
10,103,4,2,3,2,1,4,16,18,2,...,0,2,1,0.500000,11,8,4,11,32,352
11,104,4,2,3,3,1,4,16,18,2,...,0,2,1,0.500000,12,7,5,11,35,385
12,107,4,2,3,4,2,4,16,18,2,...,0,2,1,0.500000,15,6,6,11,36,396
13,181,0,1,3,0,0,4,16,29,13,...,2,3,3,1.000000,17,5,7,11,35,385
14,182,0,1,3,1,1,4,16,29,13,...,2,3,3,1.000000,18,4,8,11,32,352
15,183,0,1,3,2,1,4,16,29,13,...,2,3,3,1.000000,19,3,9,11,27,297
16,184,0,1,3,3,1,4,16,29,13,...,2,3,3,1.000000,20,2,10,11,20,220
17,188,0,1,3,4,2,4,16,29,13,...,2,3,3,1.000000,24,1,11,11,11,121
18,229,2,0,0,0,3,2,10,1,1,...,4,2,0,0.000000,4,7,1,7,7,49
19,258,2,4,0,0,3,2,8,0,0,...,5,3,1,0.333333,8,6,2,7,12,84
20,291,0,2,3,0,0,4,16,18,2,...,4,1,1,1.000000,9,5,3,7,15,105
21,292,0,2,3,1,1,4,16,18,2,...,4,1,1,1.000000,10,4,4,7,16,112
22,293,0,2,3,2,1,4,16,18,2,...,4,1,1,1.000000,11,3,5,7,15,105
23,294,0,2,3,3,1,4,16,18,2,...,4,1,1,1.000000,12,2,6,7,12,84
24,298,0,2,3,4,2,4,16,18,2,...,4,1,1,1.000000,16,1,7,7,7,49
25,319,4,2,3,0,0,4,16,18,2,...,5,2,1,0.500000,9,7,1,7,7,49
26,320,4,2,3,1,1,4,16,18,2,...,5,2,1,0.500000,10,6,2,7,12,84
27,321,4,2,3,2,1,4,16,18,2,...,5,2,1,0.500000,11,5,3,7,15,105
28,322,4,2,3,3,1,4,16,18,2,...,5,2,1,0.500000,12,4,4,7,16,112
29,326,4,2,3,4,2,4,16,18,2,...,5,2,1,0.500000,16,3,5,7,15,105
30,333,2,0,0,0,3,2,11,1,1,...,6,3,0,0.000000,4,2,6,7,12,84
31,369,2,4,0,0,3,2,8,0,0,...,7,4,1,0.250000,8,1,7,7,7,49
32,402,0,2,3,0,0,4,16,18,2,...,6,1,1,1.000000,8,17,1,17,17,289
33,403,0,2,3,1,1,4,16,18,2,...,6,1,1,1.000000,9,16,2,17,32,544
34,404,0,2,3,2,1,4,16,18,2,...,6,1,1,1.000000,10,15,3,17,45,765
35,406,0,2,3,3,1,4,16,18,2,...,6,1,1,1.000000,12,14,4,17,56,952
36,409,0,2,3,4,2,4,16,18,2,...,6,1,1,1.000000,15,13,5,17,65,1105
37,432,1,0,0,0,3,2,8,1,1,...,8,1,0,0.000000,4,12,6,17,72,1224
38,439,4,2,3,0,0,4,16,18,2,...,7,2,1,0.500000,9,11,7,17,77,1309
39,440,4,2,3,1,1,4,16,18,2,...,7,2,1,0.500000,10,10,8,17,80,1360
40,441,4,2,3,2,1,4,16,18,2,...,7,2,1,0.500000,11,9,9,17,81,1377
41,442,4,2,3,3,1,4,16,18,2,...,7,2,1,0.500000,12,8,10,17,80,1360
42,446,4,2,3,4,2,4,16,18,2,...,7,2,1,0.500000,16,7,11,17,77,1309
43,477,1,4,0,0,3,2,8,0,0,...,9,2,1,0.500000,8,6,12,17,72,1224
44,492,1,2,2,0,3,2,8,18,2,...,8,2,1,0.500000,8,5,13,17,65,1105
45,493,0,2,3,0,0,4,16,18,2,...,8,1,1,1.000000,9,4,14,17,56,952
46,494,0,2,3,1,1,4,16,18,2,...,8,1,1,1.000000,10,3,15,17,45,765
47,495,0,2,3,2,1,4,16,18,2,...,8,1,1,1.000000,11,2,16,17,32,544
48,496,0,2,3,3,1,4,16,18,2,...,8,1,1,1.000000,12,1,17,17,17,289
49,500,0,2,3,4,2,4,16,18,2,...,8,1,1,1.000000,16,15,1,15,15,225

In [26]:
#df["packet_types"] = df["packet_type"]
#df=pd.get_dummies(df, prefix=['outport', 'inport', 'packet_type'], columns=['outport', 'inport','packet_type'])

In [27]:
df.dtypes

time                    int64
outport                 int64
inport                  int64
packet_type             int64
flit_id                 int64
flit_type               int64
vnet                    int64
vc                      int64
src_ni                  int64
src_router              int64
dst_ni                  int64
dst_router              int64
pkt_chuck               int64
hop_count               int64
current_hop             int64
hop_percentage        float64
waiting_time            int64
pkt_count               int64
pkt_count_inc           int64
pkt_max                 int64
counting_index_pos      int64
counting_index_100      int64
dtype: object

In [28]:
#df['inport_3'] = 0
#df['outport_3'] = 0

In [29]:
df

,time,outport,inport,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,...,pkt_chuck,hop_count,current_hop,hop_percentage,waiting_time,pkt_count,pkt_count_inc,pkt_max,counting_index_pos,counting_index_100
0,7,2,0,0,0,3,2,8,1,1,...,1,3,0,0.00,4,7,1,7,7,49
1,11,2,4,0,0,3,2,8,0,0,...,0,4,1,0.25,8,6,2,7,12,84
2,79,0,2,3,0,0,4,16,18,2,...,1,1,1,1.00,9,5,3,7,15,105
3,80,0,2,3,1,1,4,16,18,2,...,1,1,1,1.00,10,4,4,7,16,112
4,81,0,2,3,2,1,4,16,18,2,...,1,1,1,1.00,11,3,5,7,15,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71836,2022096,4,0,4,1,1,2,10,1,1,...,11082,5,0,0.00,11,1,1,1,1,1
71837,2022103,4,0,4,2,1,2,10,1,1,...,11082,5,0,0.00,18,1,1,1,1,1
71838,2022110,4,0,4,3,1,2,10,1,1,...,11082,5,0,0.00,25,1,1,1,1,1
71839,2022117,4,0,4,4,2,2,10,1,1,...,11082,5,0,0.00,32,1,1,1,1,1
71840,2022118,4,0,0,0,3,2,11,1,1,...,11083,5,0,0.00,32,1,1,1,1,1

In [30]:
df['target'] = 0
df

,time,outport,inport,packet_type,flit_id,flit_type,vnet,vc,src_ni,src_router,...,hop_count,current_hop,hop_percentage,waiting_time,pkt_count,pkt_count_inc,pkt_max,counting_index_pos,counting_index_100,target
0,7,2,0,0,0,3,2,8,1,1,...,3,0,0.00,4,7,1,7,7,49,0
1,11,2,4,0,0,3,2,8,0,0,...,4,1,0.25,8,6,2,7,12,84,0
2,79,0,2,3,0,0,4,16,18,2,...,1,1,1.00,9,5,3,7,15,105,0
3,80,0,2,3,1,1,4,16,18,2,...,1,1,1.00,10,4,4,7,16,112,0
4,81,0,2,3,2,1,4,16,18,2,...,1,1,1.00,11,3,5,7,15,105,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71836,2022096,4,0,4,1,1,2,10,1,1,...,5,0,0.00,11,1,1,1,1,1,0
71837,2022103,4,0,4,2,1,2,10,1,1,...,5,0,0.00,18,1,1,1,1,1,0
71838,2022110,4,0,4,3,1,2,10,1,1,...,5,0,0.00,25,1,1,1,1,1,0
71839,2022117,4,0,4,4,2,2,10,1,1,...,5,0,0.00,32,1,1,1,1,1,0
71840,2022118,4,0,0,0,3,2,11,1,1,...,5,0,0.00,32,1,1,1,1,1,0

In [31]:
df.to_csv('wat-r1-mal.csv',index=False)